# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ade-verd <ade-verd@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/04/23 12:33:34 by ade-verd          #+#    #+#              #
#    Updated: 2018/04/27 18:18:53 by ade-verd         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Binary
NAME = checker

# Compiler
CC = gcc

# Directories
PROJECT_PATH = ../../
SRC_PATH = ./
SRC_PATH_MUTUAL = ../mutual/
OBJ_PATH = ../../obj/$(NAME)/
PRINTF_PATH = ../../libftprintf
LIBFT_PATH = $(PRINTF_PATH)/libft
LIB_PATH = $(LIBFT_PATH) $(PRINTF_PATH) 
INC_PATH = ../../includes \
		   $(addsuffix /includes/, $(LIB_PATH))

# Includes & libraries
SDL2_CLAGS = $(shell sdl2-config --cflags)
SDL2_LIBS = $(shell sdl2-config --libs)
CPPFLAGS = $(addprefix -I ,$(INC_PATH)) $(SDL2_CLAGS) #`sdl2-config --cflags`
LDFLAGS = $(addprefix -L ,$(LIB_PATH)) $(SDL2_LIBS) #`sdl2-config --libs`
LDLIBS = -lft -lftprintf

# Sources
SRC_NAME = \
		   main.c\
		   options.c\
		   viewer.c\

SRC_NAME_MUTUAL = \
		   reader.c\
		   heaps_manager.c\
		   stack_manager.c\
		   buffer_manager.c\
		   errors_manager.c\
		   display.c\
		   \
		   motion_swap.c\
		   motion_push.c\
		   motion_rotate.c\
		   motion_rrotate.c\
		   motion_work.c\
		   motion_apply.c\
		   \
		   counter_tools.c\
		   finder_tools.c\
		   placer.c\
		   \
		   sorter.c\
		   select_sorter.c\
		   bubble_sorter.c\

OBJ_NAME = $(SRC_NAME:.c=.o)
OBJ_NAME_MUTUAL = $(SRC_NAME_MUTUAL:.c=.o)

SRC = $(addprefix $(SRC_PATH),$(SRC_NAME)) \
	  $(addprefix $(SRC_PATH_MUTUAL),$(SRC_NAME_MUTUAL))
OBJ = $(addprefix $(OBJ_PATH),$(OBJ_NAME)) \
	  $(addprefix $(OBJ_PATH)$(SRC_PATH_MUTUAL),$(OBJ_NAME_MUTUAL))

# Flags with OS Compatibiliy
OS = $(shell uname)
ifeq ($(OS), Darwin)
	FLAGS_DEFAULT = -Werror -Wall -Wextra
endif
ifeq ($(OS), Linux)
	FLAGS_DEFAULT = -Wno-unused-result
endif
ifdef FLAGS
	ifeq ($(FLAGS), no)
		CFLAGS := $(ADDFLAGS)
	endif
	ifeq ($(FLAGS), debug)
		CFLAGS := $(FLAGS_DEFAULT) -ansi -pedantic -g $(ADDFLAGS)
	endif
else
	CFLAGS := $(FLAGS_DEFAULT) $(ADDFLAGS)
endif

# MAKEFLAGS
MAKE = make --no-print-directory -C #$(MAKEFLAGS)

# Variables
COUNTER=0

# **************************************************************************** #
# SPECIALS CHARS                                                               #
# **************************************************************************** #
LOG_CLEAR = \033[2K
LOG_UP = \033[A
LOG_NOCOLOR = \033[0m
LOG_BOLD = \033[1m
LOG_UNDERLINE = \033[4m
LOG_BLINKING = \033[5m
LOG_BLACK = \033[1;30m
LOG_RED = \033[1;31m
LOG_GREEN = \033[1;32m
LOG_YELLOW = \033[1;33m
LOG_BLUE = \033[1;34m
LOG_VIOLET = \033[1;35m
LOG_CYAN = \033[1;36m
LOG_WHITE = \033[1;37m

TITLE = $(LOG_CLEAR)$(LOG_BLUE)
END_TITLE = $(LOG_NOCOLOR)
LINKING = "--$(LOG_CLEAR)$(LOG_GREEN)✓$(LOG_NOCOLOR)\tlinking " \
				".................. $(LOG_VIOLET)$<$(LOG_NOCOLOR)"
ASSEMBLING = "--$(LOG_CLEAR)$(LOG_GREEN)✓$(LOG_NOCOLOR)\tassembling " \
			 	"............... $(LOG_YELLOW)$(NAME)$(LOG_NOCOLOR)"
OBJECTS_DEL = "--$(LOG_CLEAR)$(LOG_YELLOW)Objects$(LOG_NOCOLOR) deletion " \
				"............ $(LOG_RED)×$(LOG_NOCOLOR)"
BIN_DEL = "--$(LOG_CLEAR)$(LOG_YELLOW)Binary$(LOG_NOCOLOR) deletion " \
				"............. $(LOG_RED)×$(LOG_NOCOLOR)"

# **************************************************************************** #
# RULES                                                                        #
# **************************************************************************** #
.PHONY: all, clean, fclean, re, norme, normadev

all: $(NAME)

$(NAME): setup_SDL2 libftprintf.a $(OBJ_PATH) $(OBJ)
	@$(CC) $(OBJ) $(LDFLAGS) $(LDLIBS) -o $(NAME)
	@if [ $(COUNTER) -ne 0 ]; then echo -e $(ASSEMBLING); fi;

libftprintf.a:
	@$(MAKE) $(PRINTF_PATH) $@

setup_SDL2:
	@if [ $(OS) = Darwin ]; then make SDL2_Darwin; fi;
	@if [ $(OS) = Linux ]; then make SDL2_Linux; fi;

SDL2_Darwin:
	@if !(brew ls --versions sdl2 > /dev/null); then \
		echo -e "$(TITLE)setup sdl2$(END_TITLE)"; \
		brew update && brew install sdl2; \
	fi;
#	@sudo chown root:wheel /usr/local/bin/brew; \
#	@sudo brew link sdl2; \

SDL2_Linux:
ifndef $(shell sdl2 --version 2>/dev/null)
	@echo -e "$(TITLE)setup sdl2$(END_TITLE)"
	@sudo apt-get update
	@sudo apt-get install libsdl2-dev
endif

$(OBJ_PATH):
	@echo -e "$(TITLE)build $(NAME)$(END_TITLE)"
	@echo -e "--$(LOG_CLEAR)Flags : $(CFLAGS)"
	@mkdir -p $(OBJ_PATH)
	@mkdir -p $(OBJ_PATH)/$(SRC_PATH_MUTUAL)

$(OBJ_PATH)%.o: $(SRC_PATH)%.c 
	@$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@
	@echo -e $(LINKING)
	@$(eval COUNTER=$(shell echo $$(($(COUNTER)+1))))

clean:
	@echo -e "$(TITLE)clean $(NAME)$(END_TITLE)"
	@echo -e $(OBJECTS_DEL)
	@rm -Rf $(OBJ_PATH)
	@$(MAKE) $(PRINTF_PATH) clean_quiet

fclean:
	@echo -e "$(TITLE)fclean $(NAME)$(END_TITLE)"
	@echo -e $(OBJECTS_DEL)
	@rm -Rf $(OBJ_PATH)
	@echo -e $(BIN_DEL)
	@rm -f $(NAME)
	@$(MAKE) $(PRINTF_PATH) fclean_quiet

re: fclean all

norme:
	norminette $(SRC)
	norminette $(addprefix $(INC_PATH), *.h)

normadev: 
	~/Projects/Normadev/normadev.sh **/*.[ch]

# **************************************************************************** #
# Personal notes :                                                             #
#                                                                              #
# $@ : rule's name                                                             #
# $^ : all dependencies after ':'                                              #
# $< : corresponding dependency                                                #
# || : of there is an error, execute the command after the double pipe         #
#                                                                              #
# **************************************************************************** #
